spring.application.name=bancodigital

server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:bancodigital;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=${JWT_SECRET:cXVlcmlub2JhbmNvZGlnaXRhbDIwMjZzZWN1cmVqd3RzZWNyZXRmb3JhcGlzZW50aXR5Cg==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}